// Code generated by MockGen. DO NOT EDIT.
// Source: services/estimate.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "audiience_challenge/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// Estimate mocks base method.
func (m *MockIService) Estimate(inquiry entities.InquiryModel) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Estimate", inquiry)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Estimate indicates an expected call of Estimate.
func (mr *MockIServiceMockRecorder) Estimate(inquiry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Estimate", reflect.TypeOf((*MockIService)(nil).Estimate), inquiry)
}
